accounts/urls.py
from django.urls import path, include
from .views import register, user_login, user_logout

app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('', include('accounts.urls')),
    
]

todo/urls.py
from django.urls import path
from .views import delete, home, detail, delete, create, update

app_name = 'todo'

urlpatterns = [
    path('', home, name='home'),
    path('detail/<int:todo_id>/', detail, name='detail'),
    path('delete/<int:todo_id>/', delete, name='delete'),
    path('create/', create, name='create'),
    path('update/<int:todo_id>/', update, name='update'),
]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

#add user field to model

class Todo(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    time_created = models.DateTimeField()

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms


class UserRegistrationForm(forms.Form):
	username = forms.CharField()
	email = forms.EmailField(required=False)
	password = forms.CharField(widget=forms.PasswordInput())
	first_name = forms.CharField(required=False)
	last_name = forms.CharField(required=False)


class UserLoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

todo/forms.py
from django import forms
from .models import Todo


class ToDoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = '__all__'

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserRegistrationForm, UserLoginForm
from django.contrib import messages
from django.contrib.auth.models import User



def register(request):
    if request.method == 'GET':
        form = UserRegistrationForm()
        return render(request, 'accounts/register.html', {'form':form})

    else:
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(**form.cleaned_data)
            messages.success(request, 'Registered', 'success')
            return redirect('todo:home')
        else:
            return HttpResponse(f'{form.errors}')

def user_login(request):
    if request.method == 'GET':
        form = UserLoginForm()
        return render(request, 'accounts/login.html', {'form':form})

    else:
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, **cd)
            if user:
                login(request, user)
                messages.success(request, 'Logged in', 'success')
                return redirect('todo:home')
            else:
                return HttpResponse('Wrong User/Pass')
        else:
            return HttpResponse(f'{form.errors}')


def user_logout(request):
	logout(request)
	messages.success(request, 'logged out successfully', 'success')
	return redirect('todo:home')

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse, request
from .models import Todo
from .forms import ToDoForm
from django.contrib.auth.decorators import login_required

def home(request):
    all = Todo.objects.all()
    return render(request, 'todo/home.html', {'todos':all})


def detail(request, todo_id):
    todo = get_object_or_404(Todo, id=todo_id)
    return render(request, 'todo/detail.html', {'todo':todo})


def delete(request, todo_id):
    if not request.user.is_authenticated:
        messages.error(request, 'Login First', 'warning')
        return redirect('accounts:login')
    todo = get_object_or_404(Todo, id=todo_id)
    todo.delete()
    messages.success(request, 'Todo Deleted Successfully', 'warning')
    return redirect('todo:home')


def create(request):
    if request.method == 'GET':
        if not request.user.is_authenticated:
            messages.error(request, 'Login First', 'warning')
            return redirect('accounts:login')        
        form = ToDoForm()
        return render(request, 'todo/create.html', {'form':form})
    
    else:
        if not request.user.is_authenticated:
            messages.error(request, 'Login First', 'warning')
            return redirect('accounts:login')  
        form = ToDoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Todo created successfully', 'success')
            return redirect('todo:home')
        else:
            return HttpResponse(f'{form.errors}')

@login_required(login_url='accounts:login')
def update(request, todo_id):
    todo = get_object_or_404(Todo, id=todo_id)
    if request.method == 'GET':
        form = ToDoForm(instance=todo)
        return render(request, 'todo/update.html', {'form':form})
    else:
        form = ToDoForm(data=request.POST, instance=todo)
        if form.is_valid():
            form.save()
            messages.success(request, 'your todo updated successfully', 'success')
            return redirect('todo:detail', todo_id)

accounts/templates/accounts/login.html
{% extends "todo/base.html" %}

{% block content %}
<h3>Login Page</h3><br>

<form method="post" class="post-form">
{% csrf_token %}
{{form.as_p}} 
<button type="submit" class="btn btn-info">Login</button> 
</form>


{% endblock %}

accounts/templates/accounts/register.html
{% extends "todo/base.html" %}

{% block content %}
<h3>Register Page</h3><br>

<form method="post" class="post-form">
{% csrf_token %}
{{form.as_p}} 
<button type="submit" class="btn btn-info">Signup</button> 
</form>


{% endblock %}

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .jumbotron{
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>

</head>
<body>
    
    {% include 'todo/navbar.html' %}
    <div class="jumbotron">
        {% include 'todo/messages.html' %}
        {% block content %}  {% endblock %}
    </div>
</body>
</html>

todo/templates/todo/create.html
{% extends "todo/base.html" %}

{% block title %}Create{% endblock %}


{% block content %}
<h3>Create Todo</h3><hr>

<form method="post" class="post-form">
{% csrf_token %}
{{form.as_p}}    
<input type="submit" value="create">


</form>


{% endblock %}

todo/templates/todo/detail.html
{% extends "todo/base.html" %}

{% block title %}Detail{% endblock %}


{% block content %}

    <h4>title: {{todo.title}} </h4>
    time created: {{todo.time_created}} <hr>
    <p>body: <br>  {{todo.body}}</p>
    <a href="{% url 'todo:delete' todo.id %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'todo:update' todo.id %}" class="btn btn-info">Update</a><br>
    
{% endblock %}

todo/templates/todo/home.html
{% extends "todo/base.html" %}

{% block title %}HomePage{% endblock %}


{% block content %}
{% if not request.user.is_authenticated %}
    <a href="{% url 'accounts:register' %}" class="btn btn-info">Register</a>
    <a href="{% url 'accounts:login' %}" class="btn btn-danger">Login</a><br>
{% else %}
    <a href="{% url 'accounts:logout' %}" class="btn btn-danger">Logout</a><br>


{% endif %}

<h2>This Is HomePage</h2>

{% for todo in todos %}
{% if todo %}

    <a href="{% url 'todo:detail' todo.id %}">{{todo.title}}<br></a>  

{% endif %}
{% endfor %}

    <br> <a href="{% url 'todo:create' %}" class="btn btn-info">Create New Todo</a>

{% endblock %}

todo/templates/todo/messages.html
{% if messages %}

    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}

{% endif %}

todo/templates/todo/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
       <a class="navbar-brand" href="{% url 'todo:home' %}">Home</a>
    </div>
</nav>

todo/templates/todo/update.html
{% extends "todo/base.html" %}

{% block title %}Update{% endblock %}


{% block content %}
<h3>Update Todo</h3><hr>

<form method="post" class="post-form">
{% csrf_token %}
{{form.as_p}}    
<button type="submit" class="save btn btn-default">Update</button>

</form>


{% endblock %}